### PR TITLE
Fix rcmdcheck

### PR DESCRIPTION
**Pull request by mrustl**
Hi @ma-z-am, 

great work! Just some mini-fixes for satisfying Rcmdcheck (before GH actions workflows had a few warnings, e.g. https://github.com/KWB-R/kwb.misa/runs/6206753938?check_suite_focus=true which should be gone now!)  and using latest stable version >= 0.11.0 of kwb.utils

### CODE REVIEW

**Comment by mrustl** [comment]
Automatic checks on win/linux passed successfully (see below) ...

**Review by ma-z-am — APPROVED** [review]
lgtm

One Question: I don't get the rlang part with ".data". Why do I need to use ".data$site" instead of just "site" in the spread function?

**Comment by mrustl** [comment]
`.data$variable_name` is required to fix Rcmdcheck notes due to "unassigned global variables" (dplyr use Non Standard Evaluation instead of Rs Standard Evaluation, i.e. `site` is no real object thus `.data$site`). For use in functions Standard Evaluation needs to be the default: 

https://rlang.r-lib.org/reference/topic-data-mask-ambiguity.html?q=.data#the-data-and-env-pronouns

**Comment by mrustl** [comment]
grafik

**Pull request merged**
